$(document).ready(function(){
  $('.single-item').slick();
  $('.c-slider-principal').slick({
    fade:true
  });
  $('.c-slider-gallery').slick({
    fade:true
  });
  $('.c-slider-testimonial').slick({
    fade:true
  });
});